version: '3.8'

services:
  app:
    container_name: lyxa_product_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
      - '${APP_DEBUG_PORT}:${APP_DEBUG_PORT}'
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongodb
    restart: always
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: lyxa_product_mongodb
    env_file: .env
    ports:
      - '${MONGODB_HOST_PORT}:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge
